### ISSUE TITLE
sister project for nanomsg

### ISSUE THREAD

**Issue by glycerine** [armstrtw/rzmq#11]
Hi Whit,

Thanks again for your work on rzmq.  I used rzmq starting point for doing a nanomsg port to R just this weekend. I've put it here 

https://github.com/glycerine/nanomsgardvark

and mentioned you in the notes.

If you think it would be useful to people, would you put a link to https://github.com/glycerine/nanomsgardvark in your README?

Thanks,
Jason

**Comment by armstrtw** [comment]
is your project still active?

**Comment by glycerine** [comment]
If you mean available and working, yes . The underlying nanomsg tech was always a little flakey, so I haven't used it myself in a while.
