### ISSUE TITLE
how can I close an opened zmq socket in R?

### ISSUE THREAD

**Issue by cronacronis** [armstrtw/rzmq#17]
```R
  port = 1111
  zmq_context <- init.context()
  zmq_service.socket <- init.socket(zmq_context,"ZMQ_REQ")
  connect.socket(zmq_service.socket, paste("tcp://127.0.0.1:", port, sep = ""))
```
As I see it, I can just remove the object and expect garbage collector to waste it.
```R
  rm(zmq_service.socket, zmq_context)
```

**Comment by armstrtw** [comment]
hmm, I never did implement 'zmq_disconnect.'

Yes, you can remove the socket and the finalizer will take care of that for you, but I can see a case for wanting to keep the socket around and connect to something else...  I'll try to implement this.  Just remind me again if you don't see it show up in a few days.

-Whit

**Comment by armstrtw** [comment]
This has been committed.  Please test.

**Comment by cronacronis** [comment]
Looks like there is copy of connect now

https://github.com/armstrtw/rzmq/blob/master/R/rzmq.R#L47

**Comment by armstrtw** [comment]
that's a bug. thanks.

the disconnect function is here:
https://github.com/armstrtw/rzmq/blob/master/src/interface.cpp#L312

just not connected properly.

-Whit
