### ISSUE TITLE
No rzmq binary for R 3.3.* or 3.4.*

### ISSUE THREAD

**Issue by richierocks** [armstrtw/rzmq#24]
When following the installation instructions, [here](https://irkernel.github.io/installation/) under the current R release, 3.3.0 or R-devel (which has version 3.4.0), no `rzmq` binary is found.

```{r}
install.packages('rzmq', repos = 'http://irkernel.github.io')
## Warning in install.packages :
##   cannot open URL 'http://irkernel.github.io/bin/windows/contrib/3.3/PACKAGES.gz': HTTP status was '404 Not Found'
```

Installing from source fails for me, but installing the binary under R-3.2.5 works.

Related: https://github.com/IRkernel/IRkernel/issues/298

**Comment by armstrtw** [comment]
Interesting. I've never managed to build rzmq for windows (due to lack of an R compatible libzmq), so I don't know if the IRkernal guys have done some mods to my package to get it to build.  I think you should ask there.

**Comment by richierocks** [comment]
OK thanks, resubmitted on the IRkernel page.

https://github.com/IRkernel/IRkernel/issues/326
