### ISSUE TITLE
Any plans to get this package on CRAN?

### ISSUE THREAD

**Issue by karthik** [armstrtw/rzmq#5]
We're hoping to use this as a dependency on another package and it would be great to have you submit this to CRAN.

**Comment by JanSchulz** [comment]
I can give you shared libzmq.dll files for both 64bit and 32bit (build via the instruction on the zmq page)

**Comment by armstrtw** [comment]
They need to be built w/ R's compiler.  and I think they need to be static.  let met check.

Rtools is here:
http://cran.r-project.org/bin/windows/Rtools/

**Comment by armstrtw** [comment]
This email is from ages ago (April 2012).

ZMQLIB is bot installed on winbuilder - whatever that is.
If you need it, please provide sources and binaries that are ready for static linking with the current toolchain.

Best,
Uwe Ligges

So, we need static zmq libs built w/ the current Rtools.

-Whit

**Comment by JanSchulz** [comment]
I couldn't get it to link via rtools gcc: https://github.com/takluyver/IRkernel/issues/54#issuecomment-70934448

**Comment by armstrtw** [comment]
will be resubmitted to cran shortly.
