### ISSUE TITLE
windows builds

### ISSUE THREAD

**Issue by jeroenooms** [armstrtw/rzmq#7]
In order to provide windows builds on `CRAN`, you need to compile static libraries of `libzmq` for win32 and win64 and mail them to the CRAN maintainers. They can then deploy them on the windows build server to link when building the windows binary for `rzmq`.

See [here](https://github.com/rforge/rprotobuf/blob/master/windows/cross-compile.sh) for a script that I used to cross compile `libprotobuf.a` for the `RProtoBuf` package. You can also create `libzmq.a` on an actual windows machine obviously.

**Comment by JanSchulz** [comment]
I got it to compile on windows: https://github.com/takluyver/IRkernel/issues/54

**Comment by jeroenooms** [comment]
One other problem is that the windows version of R ships with an old version of gcc (4.6.3) that does not support C++11.

**Comment by JanSchulz** [comment]
There is now a windows build in #16

**Comment by armstrtw** [comment]
haha coming shortly.
